# Generated by Django 4.0.4 on 2022-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='protection_level',
            field=models.CharField(blank=True, choices=[('KPS', 'Keep me safe'), ('MFN', 'My friends are nice'), ('ILE', 'I live on the edge')], max_length=255, null=True),
        ),
    ]
