apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - gunicorn
            - -b
            - 0.0.0.0:8000
            - --worker-class=gevent
            - --worker-connections=1000
            - --workers=2
            - core.wsgi
          image: mlbackend
          name: mlbackend
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
