version: "3"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:8000
    command: gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=2 core.wsgi
